baseURL: "https://haydn-jones.github.io"
title: ExampleSite
paginate: 5
theme: PaperMod

enableRobotsTXT: false
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-EZV4WVKC9K

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: ExampleSite
    description: "ExampleSite description"
    author: Haydn Jones
    images: ["<link or path of image for opengraph, twitter-cards>"]

    defaultTheme: dark # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    disableSpecial1stPost: false
    comments: true
    hidemeta: false
    showtoc: true
    tocopen: true

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    label:
        text: "Home"
        icon: /apple-touch-icon.png
        iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: ExampleSite
        imageUrl: "<img location>"
        imageWidth: 120
        imageHeight: 120
        imageTitle: my image
        buttons:
            - name: Posts
              url: posts
            - name: Tags
              url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: github
          url: "https://github.com/haydn-jones"
        - name: twitter
          url: "https://twitter.com/BadBoyHayHay"
        - name: linkedin
          url: "https://www.linkedin.com/in/haydntjones/"

    analytics:
        google:
            SiteVerificationTag: "RBncEpUvyPvfBoYECYjxLlRh59LQr3EQ3XdW91ghf2o"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
        includeMatches: true
menu:
    main:
        - name: Archive
          url: archives
          weight: 1
        - name: Posts
          url: posts
          weight: 2
        - name: Search
          url: search/
          weight: 3
        - name: Categories
          url: categories/
          weight: 4
        - name: Tags
          url: tags/
          weight: 5
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary