baseURL: "https://haydn.fgl.dev/"
title: Posterior Collapse
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableGitInfo: true
googleAnalytics: G-V58YRV80SX

minify:
  disableXML: false
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: WaifuXL.com
          url: https://waifuxl.com/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Haydn's Blog"
  author: Haydn Jones

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  disableHLJS: true
  # comments: false
  # images: ["papermod-cover.png"]

  homeInfoParams:
    Title: "Posterior Collapse"
    Content: >
      Welcome to my blog, Posterior Collapse. Maybe I'll blog about machine learning here, maybe I wont.

  socialIcons:
    - name: github
      url: "https://github.com/haydn-jones"
    - name: GoogleScholar
      url: "https://scholar.google.com/citations?user=Yhmmt5YAAAAJ&hl=en"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/haydntjones/"
    - name: KoFi
      url: "https://ko-fi.com/thefuturegadgetslab"
    - name: Twitter
      url: "https://twitter.com/BadBoyHayHay"

  editPost:
    URL: "https://github.com/haydn-jones/haydn-jones.github.io/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  #analytics:
  #  google:
  #    SiteVerificationTag: "G-V58YRV80SX"

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    noClasses: true
    style: "solarized-dark256"
    pygmentsUseClasses: true

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
