baseURL: "https://haydn.fgl.dev/"
title: Posterior Collapse
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
enableGitInfo: true
googleAnalytics: G-V58YRV80SX

minify:
  disableXML: false
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        - name: WaifuXL.com
          url: https://waifuxl.com/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Haydn's Blog"
  author: Haydn Jones

  defaultTheme: dark
  disableThemeToggle: false
  ShowShareButtons: true
  disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  TocOpen: true
  ShowWordCount: false
  ShowReadingTime: false
  # comments: false

  homeInfoParams:
    Title: "Posterior Collapse"
    Content: >
      Welcome to my blog, Posterior Collapse. Maybe I'll blog about machine learning here, maybe I wont.

  socialIcons:
    - name: github
      url: "https://github.com/haydn-jones"
    - name: GoogleScholar
      url: "https://scholar.google.com/citations?user=Yhmmt5YAAAAJ&hl=en"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/haydntjones/"
    - name: KoFi
      url: "https://ko-fi.com/thefuturegadgetslab"
    - name: Twitter
      url: "https://twitter.com/BadBoyHayHay"

  editPost:
    URL: "https://github.com/haydn-jones/haydn-jones.github.io/tree/main/content/"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  label:
    text: "Posterior Collapse"
    icon: "favicon.svg"
    iconHeight: 35

  assets:
    disableHLJS: true
    favicon: "favicon.svg"
    favicon16x16: "favicon.svg"
    favicon32x32: "favicon.svg"
    apple_touch_icon: "favicon.svg"
    safari_pinned_tab: "favicon.svg"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    lineNos: true
    style: solarized-dark256

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
